### ISSUE TITLE
Patch & ProtoBuf issues

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-bigtable#44]
Hey @kolodny, can you take a look at these issues?

From https://circleci.com/gh/googleapis/nodejs-bigtable/1109:

```
> @google-cloud/bigtable@0.12.0 presystem-test /home/node/project
> git apply patches/patch-for-v4.patch || git apply patches/patch-for-v6-and-up.patch || true

error: node_modules/through2/node_modules/readable-stream/node_modules/process-nextick-args/index.js: No such file or directory
error: patch failed: node_modules/process-nextick-args/index.js:5
error: node_modules/process-nextick-args/index.js: patch does not apply
```

```
/home/node/project/system-test/read-rows-acceptance-tests.js:27
const builder = ProtoBuf.loadProtoFile({
                         ^

TypeError: ProtoBuf.loadProtoFile is not a function
```

**Comment by kolodny** [comment]
It appears this bug was introduced when protobuf was changed from v5 to v6. https://github.com/googleapis/nodejs-bigtable/commit/29c21589efe3137813fda19969897f3cab6d7f56#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L94

I think it's a matter of updating the system test to use the updated version.

The patch stuff is a red herring.

**Comment by sduskis** [comment]
@ajaaym FYI.

**Comment by ajaaym** [comment]
I will fix this today.

**Comment by ajaaym** [comment]
@sduskis @stephenplusplus @kolodny please review pull request [45](https://github.com/googleapis/nodejs-bigtable/pull/45) fixing this issue

**Comment by stephenplusplus** [comment]
Hey @ajaaym, I'm still getting the first error (about patching) locally and on the system tests: https://circleci.com/gh/googleapis/nodejs-bigtable/1131

**Comment by ajaaym** [comment]
@stephenplusplus  Is this still an issue? I cloned your branch spp--23, ran system test and its passing except that skipped one related to mutate rows.

**Comment by stephenplusplus** [comment]
Do you see this part?:

```
> @google-cloud/bigtable@0.12.0 presystem-test /home/node/project
> git apply patches/patch-for-v4.patch || git apply patches/patch-for-v6-and-up.patch || true

error: node_modules/through2/node_modules/readable-stream/node_modules/process-nextick-args/index.js: No such file or directory
error: patch failed: node_modules/process-nextick-args/index.js:5
error: node_modules/process-nextick-args/index.js: patch does not apply
```

**Comment by ajaaym** [comment]
yes fixing that.

**Comment by kolodny** [comment]
That shouldn't cause a failure, it patches processNextickArgs if it has a
broken version (ie doesn't play nicely with lolex) if, however, it was
already patched or if lolex gets updated, the patch operation will fail but
that's allowed. Note the ` || true` on that line.

It may make sense to redirect stderr to Dev/null to avoid this
misunderstanding in the future

**Comment by ajaaym** [comment]
yeah command prints error and exists with return code 0

**Comment by kolodny** [comment]
Just making sure we're all on the same page. @stephenplusplus  @ajaaym can this issue be closed or are there still other blockers?

**Comment by stephenplusplus** [comment]
Is it possible it's fixed now, which is why we're getting the error? In other words, can we remove the patching?

**Comment by kolodny** [comment]
Not really, this is still broken in through2, once https://github.com/rvagg/through2/pull/88 is merged and published, we would need to update our dependency of through2, then I believe the patching code can be removed. We can potentially change the `presystem-test` line in `package.json` from this:

```
"presystem-test": "git apply patches/patch-for-v4.patch || git apply patches/patch-for-v6-and-up.patch || true",
```

to this:

```
"presystem-test": "git apply patches/patch-for-v4.patch 2>/dev/null && echo patched successful || git apply patches/patch-for-v6-and-up.patch 2>/dev/null && echo patched successful || echo patch not needed",
```

but I figured it wasn't really worth it. I'm open to that change if other feel it's warranted

**Comment by stephenplusplus** [comment]
Sorry, I think I need more time to process what's going on, and this isn't that important, so I'm kind of deferring that for now :) The part I'm confused about is why some systems would need the patch and not others.

**Comment by kolodny** [comment]
All systems need a patch. Some need the node v4 patch, some need the non v4 patch. Once it's patched the first time it will always work and patching again will fail but that's OK. Let me know if that clears it up

**Comment by stephenplusplus** [comment]
Gotcha, thanks. I'll close this one.
